---
# tasks file for ansible-role-hadoop-stop-services

# Get Hadoop Ambari server
- name: Get Hadoop Ambari instances
  ec2_instance_info:
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    region: "{{ region }}"
    filters:
      # "tag:client-name": "*{{ client_name }}*"
      "tag:Name": "*{{ application }}*"
      # "tag:environment": "*{{ env }}*"
  register: ec2_ambari_instances

- name: Set Hadoop Ambari instance IP as fact
  set_fact:
    ambari_ip: "{{ ec2_ambari_instances.instances[0].private_ip_address }}"
  when: ec2_ambari_instances.instances[0] is defined

- include: "{{ operation }}.yml"
  when: ambari_ip is defined