---

# Shell command that connects to ambari server and executes the start all services script via the control server.
# - name: Start Hadoop Processes
#   shell: "ssh -A -o 'StrictHostKeyChecking=no' jenkins@{{ control_server }} sudo ssh -t -A {{ ambari_ip }} /opt/ibm/fci/utils/fci-hadoop.start_all_services.sh"

- name: Start Hadoop Processes
  shell: "ssh -oStrictHostKeyChecking=no -q jenkins@{{ ambari_ip }} sudo su - -c /opt/ibm/fci/utils/fci-hadoop.start_all_services.sh"